client_config_backend: settings
client_config:
  client_id: 1042078252892-ollgl1d3cm2hb303ostesebfbr8f88k0.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
  - https://www.googleapis.com/auth/drive.metadata